workspace(name = "salvo")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "com_google_protobuf",
    remote = "https://github.com/protocolbuffers/protobuf",
    tag = "v3.10.0",
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

local_repository(
    name = "salvo_build_config",
    path = ".",
)

load("//bazel:python_dependencies.bzl", "salvo_python_dependencies")

salvo_python_dependencies()

load("@salvo_pip3//:requirements.bzl", salvo_pip3 = "install_deps")

salvo_pip3()